name: Deploy Angular to GitHub Pages

# run on push to main
on:
  push:
    branches:
      - main

# give workflow permission to write repository contents and pages
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build --if-present -- --configuration production --base-href "/Portfolio/"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio
